### ISSUE TITLE
Why it does not work?

### ISSUE THREAD

**Issue by ronvaleron** [josh26turner/Ambilight#5]
It doesn't work at all. I installed everything according to the instructions, I started it, but the diodes do not light up at all with the colors they should. Even if everything is red, the backlight has both white and green colors

**Comment by josh26turner** [comment]
Hi, does setting the background colour work? 

If you modify the config file to set `background = [254, 0, 0];` then run:
```
$ ambilight-color
```
Does it make the LEDs red?

Alternatively, try 
```
$ ambilight 254 0 0
```
And see if that sets all the LEDs to red.

**Comment by ronvaleron** [comment]
Hello. Yes, this case work. I tried change and static color ok. background = [GREEN, RED, BLUE]; - is it correct colors?
Ow. I just  see. In yoer example colors has another order - $ ambilight [red green blue]
Driver 4070super, OS Ubuntu 24
Where I must change it? In the arduino.ino, right?
I tried change color order in the ino, and for ambilight-color it is work like your RGB, but ambilight  still not  work.
It's flashin and essential has white color.

`brightness = 100;
leds_on_top = 21;
leds_on_side = 12;

pixels_to_process = 30;

pixels_per_led_top = 121;
pixels_per_led_side = 120;

vertical_pixel_gap = 0;
vertical_pixel_count = 1440;

horizontal_pixel_gap = 9;
horizontal_pixel_count = 2560;

background = [0, 0, 0];

arduino_device_name = "/dev/ttyUSB0";`

**Comment by josh26turner** [comment]
Interestingly the background order should be `[RED, GREEN, BLUE]` like the other. I have spotted a mistake in the README, where it says `ambilight <red> <green> <blue>` it should be `ambilight-color <red> <green> <blue>` and without arguments it should set it from the colour from the config file. (I have just amended the README)

As it doesn't seem to be setting the colors on the LEDs correctly I think we can start looking why it isn't set correctly. Is `NUM_LEDS` in ambilight.ino set correctly? From your config file it should be 45 (2 * leds_on_side + leds_on_top). And is the data pin set correctly? I think it probably is as the LEDs seem to be doing something when talked to.

**Comment by ronvaleron** [comment]
It  is insight!! You have use only 3 sides - left, top, right. But I use 4 sides - left, top, right, bottom!!!
My LED strip goes from the bottom left corner counterclockwise. I have 66 diodes in total. 21 on the top and bottom and 12 on the sides. This explains why just the backlight works, even though one color is mixed up.




![photo_2024-11-01_15-37-33](https://github.com/user-attachments/assets/806fca56-1501-455b-be95-5d1e0da45b3d)

**Comment by ronvaleron** [comment]
![photo_2024-11-01_15-37-33](https://github.com/user-attachments/assets/04e88bea-ba4c-48ea-a9e7-82d4f0d7b0cb)

**Comment by josh26turner** [comment]
Aha! Yes, that is the difference. I have just pushed a new branch called [`bottom-leds`](https://github.com/josh26turner/Ambilight/tree/bottom-leds) that has an attempt to add bottom LED writing to the ambilight utility. Could you check it out, rebuild and try that? I have not tested the code as I don't have LEDs on the bottom so I can't. It is unlikely to work but if you could post any error that would be helpful :)

**Comment by ronvaleron** [comment]
Ok. I'll check it tonight. Just tell me, what is a direction to led strip do you  use?

**Comment by josh26turner** [comment]
Starting in the bottom left corner, then going clockwise (facing the monitor screen, so up from the bottom left corner) round to the end. The code can be modified for another order.

**Comment by ronvaleron** [comment]
It would be great if you could set the direction in the config, like cw = clockwise and ccw = counterclockwise.
Yes, now it works, but i still have problem with counterclockwise direction. And the colors lack saturation, I would like to increase it a little. 
![photo_2024-11-01_20-45-35](https://github.com/user-attachments/assets/f8683407-dc14-4058-a935-40c4859974fa)
